### ISSUE TITLE
Load configs from a file or env var

### ISSUE THREAD

**Issue by NatoBoram** [TheyCallMeLinux/Mounit#1]
Nice bot :) Here's some suggestions related to configs

https://github.com/TheyCallMeLinux/Mounit/blob/d6f8d530fafb3c5f208e7a4739c5df841b6561c8/mounit.py#L13-L17

These variables could be loaded from the environment with `os.getenv("MOUNIT_MINTIME")`. Alternatively, configs could be loaded from `~/.config/Mounit/config.json`. https://www.programiz.com/python-programming/json

This allows you to run the bot without accidentally committing the bot's configs to the Git repo.

Access to `~/.config` can be done with [appdirs](https://github.com/ActiveState/appdirs) to keep it cross-platform

**Comment by TheyCallMeLinux** [comment]
Thank you @NatoBoram  :) I was planning on doing something like that and fell short on time and documentation. Your links are very helpful I will certainly try to add this soon

**Comment by TheyCallMeLinux** [comment]
@NatoBoram  Partly implemented your recommendations but have some major overhaul to do. Now it should also run fine(ish) with python 3.8
